apiVersion: v1
kind: Service
metadata:
  name: sk032-backend
  namespace: class-2
spec:
  selector:
    app: sk032-backend
  ports:
    - name: http
      port: 5000
      targetPort: 5000
  type: ClusterIP
